export const vocaloidBirthdays: Record<number, { day: number; names: string[] }[]> = {
    1: [
      { day: 14, names: ['Prima', 'Unity-chan!'] },
      { day: 15, names: ['LEON & LOLA'] },
      { day: 19, names: ['Shian'] },
      { day: 25, names: ['COKO'] },
      { day: 27, names: ['IA', 'OИE'] },
      { day: 28, names: ['Fukase'] },
      { day: 30, names: ['Megurine Luka'] },
    ],
    2: [
      { day: 3, names: ['Tsuina-chan'] },
      { day: 4, names: ['CYBER DIVA'] },
      { day: 5, names: ['Utane Uta (ngày đầu tiên được sử dụng trên niconico)'] },
      { day: 10, names: ['Xin Hua'] },
      { day: 13, names: ['Tohoku Kiritan'] },
      { day: 14, names: ['kokone', 'UNI'] },
      { day: 16, names: ['Yumemi Nemu'] },
      { day: 17, names: ['KAITO'] },
      { day: 22, names: ['Mirai Komachi'] },
      { day: 24, names: ['Chis-A'] },
    ],
    3: [
      { day: 2, names: ['Hanakuma Chifuyu']},
      { day: 3, names: ['anon', 'kanon'] },
      { day: 4, names: ['Utane Uta (ngày đầu tiên bắt đầu dự án)'] },
      { day: 27, names: ['PASTEL', 'HALO']},
      { day: 28, names: ['Macne Nana', 'Macne Petit'] },
      { day: 30, names: ['MEIKA Hime', 'Mikoto'] },
    ],
    4: [
      { day: 1, names: ['Kasane Teto'] },
      { day: 3, names: ['AiKO'] },
      { day: 6, names: ['Aoki Lapis'] },
      { day: 12, names: ['Yuezheng Ling'] },
      { day: 13, names: ['Stardust'] },
      { day: 18, names: ['Hibiki Koto'] },
      { day: 25, names: ['Roro (VY2)', 'Kotonoha Akane', 'Aoi'] },
      { day: 29, names: ['SEKAI'] }
    ],
    5: [
      { day: 6, names: ['MAYU'] },
      { day: 9, names: ['V Flower', 'Fuiro'] },
      { day: 14, names: ['Nekomura Iroha'] },
      { day: 16, names: ['Kohaku Rikka'] },
      { day: 20, names: ['Mo Qingxian', 'Cangqiong'] },
      { day: 30, names: ['Ui'] }
    ],
    6: [
      { day: 11, names: ['Masaoka Azuki'] },
      { day: 13, names: ['ANRI'] },
      { day: 20, names: ['ZOLA PROJECT'] },
      { day: 21, names: ['Sukone Tei'] },
      { day: 26, names: ['GUMI'] },
      { day: 29, names: ['Sweet ANN'] },
    ],
    7: [
      { day: 1, names: ['MIRIAM'] },
      { day: 5, names: ['Kyomachi Seika'] },
      { day: 7, names: ['KAFU'] },
      { day: 11, names: ['YANHE'] },
      { day: 12, names: ['Luo Tianyi'] },
      { day: 13, names: ['MYK-IV'] },
      { day: 14, names: ['SONiKA', 'Tonio'] },
      { day: 16, names: ['v4 flower'] },
      { day: 22, names: ['Haiyi'] },
      { day: 26, names: ['Haruno Sora'] },
      { day: 27, names: ['Sachiko'] },
      { day: 30, names: ['Otomachi Una'] },
      { day: 31, names: ['Camui Gackpo'] },
    ],
    8: [
      { day: 5, names: ['ARSLOID', 'galaco'] },
      { day: 12, names: ['Xingchen (Stardust)'] },
      { day: 18, names: ['Eleanor Forte'] },
      { day: 25, names: ['Lily'] },
      { day: 30, names: ['LUMi', 'SeeU'] },
      { day: 31, names: ['Hatsune Miku'] },
    ],
    9: [
      { day: 1, names: ['VY1'] },
      { day: 3, names: ['Ngày của GUMI'] },
      { day: 9, names: ['Rana', 'Natsuki'] },
      { day: 10, names: ['YOHIOloid'] },
      { day: 13, names: ['Kobayashi Matcha'] },
      { day: 15, names: ['Tsurumaki Maki'] },
      { day: 26, names: ['Miyamai Moca', 'And Uge'] },
      { day: 27, names: ['Yamine Renri'] },
      { day: 30, names: ['WhiteCUL'] },
    ],
    10: [
      { day: 2, names: ['Yuezheng Longya'] },
      { day: 7, names: ['RUBY'] },
      { day: 8, names: ['Ryuto'] },
      { day: 12, names: ['Adachi Rei'] },
      { day: 16, names: ['Chika'] },
      { day: 21, names: ['Mew'] },
      { day: 25, names: ['RIME'] },
      { day: 27, names: ['Tohoku Zunko'] },
      { day: 30, names: ['Amehare Hau'] },
      { day: 31, names: ['CYBER SONGMAN'] },
    ],
    11: [
      { day: 1, names: ['Akita Neru'] },
      { day: 5, names: ['MEIKO'] },
      { day: 13, names: ['HARU'] },
      { day: 14, names: ['Kasukabe Tsumugi'] },
      { day: 20, names: ['DAINA', 'DEX'] }, 
      { day: 21, names: ['Yowane Haku'] },
    ],
    12: [
      { day: 4, names: ['Hiyama Kiyoteru', 'Kaai Yuki', 'SF-A2 Miki', 'Tsukuyomi Ai', 'Shouta'] },
      { day: 5, names: ['Zundamon'] },
      { day: 8, names: ['Utatane Piko'] },
      { day: 10, names: ['Zhiyu Moke'] },
      { day: 16, names: ['Tone Rion'] },
      { day: 17, names: ['ROSA', 'Yokune Ruko'] },
      { day: 18, names: ['MAIKA'] },
      { day: 19, names: ['AiSuu']},
      { day: 21, names: ['OLIVER', 'POPY', 'ROSE'] },
      { day: 22, names: ['Kizuna Akari', 'Yuzuki Yukari'] },
      { day: 23, names: ['Bruno & Clara'] },
      { day: 24, names: ['CUL', 'Merli'] },
      { day: 26, names: ['Chiyu'] },
      { day: 27, names: ['Kagamine Rin', 'Kagamine Len'] },
    ],
  }
  